name: Linter

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.6.0
        with:
          pixi-version: v0.20.1
          environments: lint
          frozen: true

      - name: Run linter
        run: pixi run lint
